name: Trackquery

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Selecting Environment
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/thereisnothinginhere/nowayterminal/main/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/thereisnothinginhere/nowayterminal/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/thereisnothinginhere/nowayterminal/main/loop.bat -OutFile loop.bat
    - name: Making the Ground Ready
      run: Expand-Archive ngrok.zip
    - name: Watering the Lawns
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Painting the Walls
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
    - name: Grabbing the Chairs
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region in 3389"'
    - name: Starting the Process failure
      run: cmd /c start.bat
    - name: Wait do your best
      run: cmd /c loop.bat
